import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/Navbar";

export const metadata = {
  title: "Finance Manager",
  description: "Generated by Hardik",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="dark">
      <body data-theme="dark">
        <Navbar />
        {children}
      </body>
    </html>
  );
}
